// This file is generated by Slice Machine. Update with care!

import SectionOfWebsite from './SectionOfWebsite';

export {
	SectionOfWebsite,
};

export const components = {
	section_of_website: SectionOfWebsite,
};
